
import React from 'react';
import { ExternalLink, Star, Quote, Building2, TrendingDown, UserCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const CaseStudiesPage: React.FC = () => {
  return (
    <div className="pb-24">
      <section className="pt-20 pb-20 bg-purple-deep">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h1 className="text-5xl font-black font-heading mb-6">Client <span className="text-accent-gold">Success Stories</span></h1>
          <p className="text-xl text-gray-300 max-w-2xl mx-auto">
            See how High Risk Sims is helping RTOs across Australia modernize their delivery and improve their audit results.
          </p>
        </div>
      </section>

      <section className="py-24 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-24">
        {/* Placeholder 1 */}
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className="order-2 lg:order-1 space-y-8">
            <div className="inline-flex items-center px-4 py-1 bg-cyan-400/10 border border-cyan-400/20 rounded-full text-cyan-400 text-xs font-black uppercase tracking-widest">
              Construction RTO - SE Queensland
            </div>
            <h2 className="text-4xl font-black font-heading">Reducing Equipment Fatigue by 40%</h2>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                <TrendingDown className="text-red-400 mb-2" />
                <div className="text-2xl font-black">40%</div>
                <div className="text-xs text-gray-500 uppercase">Wear & Tear Reduction</div>
              </div>
              <div className="bg-white/5 p-4 rounded-xl border border-white/10">
                <UserCheck className="text-green-400 mb-2" />
                <div className="text-2xl font-black">15%</div>
                <div className="text-xs text-gray-500 uppercase">Increased Pass Rate</div>
              </div>
            </div>
            <p className="text-gray-400 leading-relaxed">
              "We used to spend 5 hours per student in the cabin just for basic familiarization. Now, they do those 5 hours in the High Risk Sims booth. By the time they touch the real crane, they already know the controls and the site layout. It's transformed our cost-to-deliver."
            </p>
            <div className="flex items-center space-x-4 border-t border-white/5 pt-6">
              <div className="w-12 h-12 rounded-full bg-accent-gold/20 flex items-center justify-center font-bold text-accent-gold">GM</div>
              <div>
                <div className="font-bold">General Manager</div>
                <div className="text-xs text-gray-500 uppercase">Training Solutions Australia</div>
              </div>
            </div>
          </div>
          <div className="order-1 lg:order-2">
            <div className="aspect-video bg-white/5 rounded-[2.5rem] border border-white/10 overflow-hidden relative group">
              <img 
                src="https://picsum.photos/id/122/1000/600" 
                alt="Case Study 1" 
                className="w-full h-full object-cover grayscale opacity-50 group-hover:grayscale-0 transition-all duration-700"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#1a102e] via-transparent to-transparent"></div>
            </div>
          </div>
        </div>

        {/* Placeholder 2 */}
        <div className="grid lg:grid-cols-2 gap-12 items-center">
          <div className="aspect-video bg-white/5 rounded-[2.5rem] border border-white/10 overflow-hidden relative group">
            <img 
              src="https://picsum.photos/id/133/1000/600" 
              alt="Case Study 2" 
              className="w-full h-full object-cover grayscale opacity-50 group-hover:grayscale-0 transition-all duration-700"
            />
            <div className="absolute inset-0 bg-gradient-to-t from-[#1a102e] via-transparent to-transparent"></div>
          </div>
          <div className="space-y-8">
            <div className="inline-flex items-center px-4 py-1 bg-accent-gold/10 border border-accent-gold/20 rounded-full text-accent-gold text-xs font-black uppercase tracking-widest">
              Logistics Training Provider - Sydney
            </div>
            <h2 className="text-4xl font-black font-heading">Seamless ASQA Audits with RTOWebLMS</h2>
            <p className="text-gray-400 leading-relaxed">
              Facing an ASQA audit is usually a time of high stress. However, with the evidence trail generated by High Risk Sims and the tracking in RTOWebLMS, we were able to provide auditors with a perfect record of every student's practical attempt, including timestamped collision logs and competency markers.
            </p>
            <div className="p-6 bg-[#2D1B4E] rounded-2xl border border-purple-500/20 italic text-gray-300 relative">
              <Quote className="absolute -top-3 -left-3 text-accent-gold opacity-20 w-12 h-12" />
              "The auditors were genuinely impressed with the level of detail. They haven't seen anything like this integration in the RTO space before."
            </div>
            <div className="flex items-center space-x-4 border-t border-white/5 pt-6">
              <div className="w-12 h-12 rounded-full bg-cyan-400/20 flex items-center justify-center font-bold text-cyan-400">CC</div>
              <div>
                <div className="font-bold">Compliance Coordinator</div>
                <div className="text-xs text-gray-500 uppercase">National Training Group</div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 bg-[#120a1f] text-center">
        <div className="max-w-2xl mx-auto px-4">
          <h2 className="text-3xl font-black font-heading mb-6">Become Our Next Success Story</h2>
          <Link to="/contact" className="inline-block bg-accent-gold text-[#1a102e] px-10 py-4 rounded-full font-bold hover:scale-105 transition-all shadow-xl shadow-gold/10">
            Enquire Now
          </Link>
        </div>
      </section>
    </div>
  );
};

export default CaseStudiesPage;
